---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load the required packages. As this code is being written in R and not the 
# default Python as used in the course, explanations of each package used and justification for doing so is included here.

# Package used for handling rjson files.
library(rjson)
# Package used for data pre-processing. Equivalent of Pandas for Python.
library(dplyr)
# Regression and ML package. Equivalent of scikit-learn or PyCaret for Python.
library(caret)
# Graphing/visualisation package. Equivalent of matplotlib for Python.
library(ggplot2)
# Football pitch visualisation package.
library(ggsoccer)
# Package for data wrangling
library(tidyr)

# Import the Wyscout Data
england <- fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/events/events_England.json")
france <- fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/events/events_France.json")
germany <- fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/events/events_Germany.json")
italy <- fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/events/events_Italy.json")
spain <- fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/events/events_Spain.json")
```

```{r}
# Get events
england.events <- data.frame(do.call(rbind,england),stringsAsFactors = FALSE)
france.events <- data.frame(do.call(rbind,france),stringsAsFactors = FALSE)
germany.events <- data.frame(do.call(rbind,germany),stringsAsFactors = FALSE)
italy.events <- data.frame(do.call(rbind,italy),stringsAsFactors = FALSE)
spain.events <- data.frame(do.call(rbind,spain),stringsAsFactors = FALSE)

all.events <- rbind(england.events,france.events,germany.events,italy.events,
                    spain.events)
```

```{r}
# Get teams
teams <- data.frame(do.call(rbind,fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/teams.json")),stringsAsFactors = FALSE)

teams$name <- as.character(teams$name)
teams$wyId <- as.numeric(teams$wyId)
```

```{r}
# Get players
players <- fromJSON(file = "players.json")
players <- data.frame(do.call(rbind,players),stringsAsFactors = FALSE)
players$role <- as.data.frame(do.call(rbind, players$role))
```


```{r}
# Get matches

england.matches <- data.frame(do.call(rbind,fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/matches/matches_England.json")),stringsAsFactors = FALSE)
france.matches <- data.frame(do.call(rbind,fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/matches/matches_France.json")),stringsAsFactors = FALSE)
germany.matches <- data.frame(do.call(rbind,fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/matches/matches_Germany.json")),stringsAsFactors = FALSE)
italy.matches <- data.frame(do.call(rbind,fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/matches/matches_Italy.json")),stringsAsFactors = FALSE)
spain.matches <- data.frame(do.call(rbind,fromJSON(file="/Users/jamescronly/datasciencecoursera/Player Scouting/matches/matches_Spain.json")),stringsAsFactors = FALSE)

matches <- rbind(england.matches,france.matches,germany.matches,italy.matches,
                 spain.matches)
```


```{r}

# Unnest and collate position data

test <- all.events

test$positions <- as.data.frame(do.call(rbind, test$positions))

test$positions$V1 <- as.data.frame(do.call(rbind, test$positions$V1))
test$positions$V2 <- as.data.frame(do.call(rbind, test$positions$V2))

y1 <- test$positions$V1$y
x1 <- test$positions$V1$x
y2 <- test$positions$V2$y
x2 <- test$positions$V2$x

y1 <- as.data.frame(do.call(rbind, y1))
x1 <- as.data.frame(do.call(rbind, x1))
y2 <- as.data.frame(do.call(rbind, y2))
x2 <- as.data.frame(do.call(rbind, x2))

locations <- as.data.frame(cbind(x1, y1, x2, y2))
colnames(locations) <- c("x1","y1","x2","y2")
final <- cbind(select(test, -positions),locations)

# Select variables of interest according to SPADL format
# SPADL.select is now tidy apart from tags variable

SPADL.select <- final %>% select(matchId, 
                                      matchPeriod,
                                      eventSec,
                                      teamId,
                                      playerId,
                                      x1,y1,x2,y2,
                                      eventName,
                                      subEventName,
                                      tags)

SPADL.select$matchId <- as.numeric(SPADL.select$matchId)
SPADL.select$matchPeriod <- as.character(SPADL.select$matchPeriod)
SPADL.select$eventSec <- as.numeric(SPADL.select$eventSec)
SPADL.select$teamId <- as.numeric(SPADL.select$teamId)
SPADL.select$playerId <- as.numeric(SPADL.select$playerId)
SPADL.select$eventName <- as.character(SPADL.select$eventName)
SPADL.select$subEventName <- as.character(SPADL.select$subEventName)
```

```{r}
# Find events only conducted by liverpool
liverpool <- filter(teams, name == "Liverpool")
liverpool_Id <- liverpool$wyId

liverpool.events <- filter(SPADL.select, teamId %in% liverpool_Id)

# Find events that only occur within liverpool games
liverpool.matches <- filter(england.matches, grepl("Liverpool",label))

liverpool.match.events <- filter(SPADL.select, 
                                 matchId %in% liverpool.matches$wyId)

```

```{r warning=FALSE}
# Build Possession Chains. Possession chain starts when Liverpool gains control of the ball. Possession ends as soon as an events has been recorded by opposition. New chain starts when liverpool regain possession.

# t.liverpool.match.events <- liverpool.match.events[1:(nrow(model.data.frame)-1),]

t.liverpool.match.events <- liverpool.match.events[1:(nrow(liverpool.match.events)-1),]

# Are Liverpool in possession?
t.liverpool.match.events$in.possession <-
        lapply(t.liverpool.match.events$teamId,FUN 
               = function(x) 
                       if(x == 1612) {
                       "YES"}
               else return("NO"))

t.liverpool.match.events$in.possession <- 
        as.character(t.liverpool.match.events$in.possession)

# Is this their first possession?

t.liverpool.match.events$first_possession[1] <- "YES"

for (i in 2:nrow(t.liverpool.match.events)) {
        if(t.liverpool.match.events$in.possession[i] == "YES" &
           t.liverpool.match.events$in.possession[i-1] == "NO") {
                t.liverpool.match.events$first_possession[i] <- "YES"
        } else t.liverpool.match.events$first_possession[i] <- "NO"
}

# Assign possession number
possession_number <- 0

for (i in 1:nrow(t.liverpool.match.events)) {
        if(t.liverpool.match.events$in.possession[i] == "YES" &
           t.liverpool.match.events$first_possession[i] == "YES") {
                possession_number <- possession_number + 1
                t.liverpool.match.events$possession_count[i] <- 
                        possession_number
        } 
        if(t.liverpool.match.events$in.possession[i] == "YES" &
           t.liverpool.match.events$first_possession[i] == "NO") {
                t.liverpool.match.events$possession_count[i] <-
                        possession_number
        }
        if(t.liverpool.match.events$in.possession[i] == "NO") {
                t.liverpool.match.events$possession_count[i] <- "OPPO"
        }
}

# Find end of possession

for (i in 2:(nrow(t.liverpool.match.events)-1)) {
        if(t.liverpool.match.events$possession_count[i] == "OPPO") {
                t.liverpool.match.events$final_action[i] <- "OPPO"
        }
        if(t.liverpool.match.events$possession_count[i] != "OPPO" &
           t.liverpool.match.events$possession_count[i+1] == "OPPO") {
                t.liverpool.match.events$final_action[i] <- 1
        }
        if(t.liverpool.match.events$possession_count[i] != "OPPO" &
           t.liverpool.match.events$possession_count[i+1] != "OPPO") {
                t.liverpool.match.events$final_action[i] <- 0
        }
}
        
# Does an opposition shot occur within 10 events of losing possession?
              
for(i in 2:(nrow(t.liverpool.match.events)-10)) {
        if(t.liverpool.match.events$final_action[i] == "OPPO") {
                t.liverpool.match.events$shot[i] <- "OPPO"
        }
        if(t.liverpool.match.events$final_action[i] == 0) {
                t.liverpool.match.events$shot[i] <- 0
        }
        if(t.liverpool.match.events$final_action[i] == 1) {
                next_ten_actions <- t.liverpool.match.events[i+1:i:10,]
                opposition_actions <- filter(next_ten_actions,
                                             teamId != 1612)
                opposition_shots <- filter(opposition_actions,
                                           eventName == "Shot")
                
                if(nrow(opposition_shots) == 0) {
                        t.liverpool.match.events$shot[i] <- 0
                } 
                if(nrow(opposition_shots) > 0) {
                        t.liverpool.match.events$shot[i] <- 1
                        }
                }
        }


# Filter to just Liverpool events

model.data.frame <- filter(t.liverpool.match.events, teamId == 1612)

# Select required variables

model.data.frame <- model.data.frame %>% select(possession_count,
                           x1,
                           y1,
                           x2,
                           y2,
                           shot)

# Allocate shot to rest of possession chain

for (i in 2:(nrow(model.data.frame)-10)) { 
        if(model.data.frame$shot[i] == 1) {
                current_possession <- model.data.frame$possession_count[i]
                for(j in 1:nrow(model.data.frame)) {
                        if(model.data.frame$possession_count[j] ==
                           current_possession) {
                                model.data.frame$shot[j] <- 1
                           }
                }
        }
}

# Omit last 6 actions

model.data.frame <- model.data.frame[1:(nrow(model.data.frame)-6),]
model.data.frame$shot <- as.factor(model.data.frame$shot)
```

```{r}
# Build logistic regression model on Liverpool shot conceded data

set.seed(12345)
tc <- trainControl(method = "repeatedcv", number = 10)
shot.model <- train(data = model.data.frame,
                    shot ~ x1 + y1 + x2 + y2, 
                    method = 'glm',
                    family= binomial)

try.out <- SPADL.select

# Use model on every action in all five leagues to find shot concede probability for each action

prediction <- predict(shot.model, newdata = try.out, type = "prob")

colnames(prediction) <- c("no_shot", "shot")

SPADL.final <- cbind(SPADL.select, prediction)

```

```{r}
# Sum probabilities per player

prob.player <- SPADL.final %>%
        group_by(playerId) %>%
        summarise(Total_Shot = sum(shot),
                  Mean_Shot = mean(shot),
                  events = n(),
                  mean_y_location = mean(y1),
                  Sigma_Shot = sd(shot))


# Eliminate events assigned to no player and sort by ascending

prob.player <- prob.player[-1,]

defenders <- filter(players, role$code2 == "DF")

prob.player.defenders <- filter(prob.player, playerId %in% defenders$wyId)
```

```{r}
# Find liverpool stats

liverpool.players <- filter(players, currentTeamId == 1612, role$code2 == "DF")

liverpool.scores <- filter(prob.player, playerId %in% liverpool.players$wyId)

```

```{r}
# Assign Correct names to players

for (i in 1:nrow(prob.player.defenders)) {
        for (j in 1:nrow(players)) {
                if(prob.player.defenders$playerId[i] ==
                   players$wyId[j]) {
                        prob.player.defenders$name[i] <-
                                players$shortName[j]
                        prob.player.defenders$birthDate[i] <-
                                players$birthDate[j]
                   }
        }
}
```


```{r, fig.width= 8, fig.height=6}
# Build graph of number of events against total shot probability

library(ggrepel)

graph1 <- ggplot(prob.player.defenders) +
        geom_point(aes(events, Total_Shot),
                   color = "Black",
                   shape = 5,
                   size = 0.5,
                   alpha = 1/2) +
        geom_text_repel(data = subset(filter(prob.player.defenders, 
                                       playerId %in% liverpool.players$wyId)),
                  aes(events, Total_Shot, label = name),
                  colour = "red",
                  size = 5,
                  box.padding = 1.5,
                  vjust = 0.5,
                  max.overlaps = Inf) +
        theme_bw() +
        xlim(0,5000) +
        xlab("Events") +
        ylab("Cumulative Shot Probabilities")

graph1

graph2 <- ggplot(prob.player.defenders) +
        geom_point(aes(events, Mean_Shot),
                   color = "Black",
                   shape = 5,
                   size = 0.5,
                   alpha = 1/2) +
        geom_text_repel(data = subset(filter(prob.player.defenders, 
                                       playerId %in% liverpool.players$wyId)),
                  aes(events, Mean_Shot, label = name),
                  colour = "red",
                  size = 5,
                  box.padding = 2,
                  segment.linetype = 2,
                  max.overlaps = Inf) +
        theme_bw() +
        xlab("Events") +
        ylab("Shot Probability per Event")

graph2

```

```{r}
# Find Centre-Halfs

centre_backs <- filter(prob.player.defenders, mean_y_location > 30 &
                              mean_y_location < 70)

centre_backs <- arrange(centre_backs, Mean_Shot)

# Find players with more than 500 events

centre_backs <- filter(centre_backs, events > 1000)
centre_backs$birthDate <- strptime(centre_backs$birthDate, format = "%Y-%m-%d")

start_of_transfer_window <- strptime("2018-07-01", format = "%Y-%m-%d")

centre_backs$age <- difftime(start_of_transfer_window,
                             centre_backs$birthDate,
                             units="weeks")

centre_backs$age <- centre_backs$age/52

# Look for players younger than 30

centre_backs <- filter(centre_backs, age < 30)

# Shortlist after full-backs have been excluded

shortlist <- c("K. Koulibaly",
               "M. Hummels",
               "L. Klostermann",
               "N. Elvedi",
               "J. Boateng",
               "M. Tisserand",
               "P. Retsos",
               "G. Jung",
               "Nacho",
               "J. Gelin",
               "P. Kimpembe",
               "Bartra",
               "Juan Jesus",
               "Jordi Amat",
               "G. Ferrari",
               "A. Djiku")

shortlist.data <- filter(centre_backs, name %in% shortlist)

shortlist.data$age <- round(shortlist.data$age, 1)

shortlist.data$price <- c(54,54,10.8,15.3,40.5,6.75,16.2,2.7,31.5,3.15,27,19.8,
                          11.7,4.5,9,7.2)

shortlist.table <- select(shortlist.data, -c(playerId, 
                                             mean_y_location,
                                             birthDate))

shortlist.table <- select(shortlist.table, name, price, age, Mean_Shot,
                          Sigma_Shot, events, Total_Shot)

shortlist.table$Mean_Shot <- round(shortlist.table$Mean_Shot, 5)
shortlist.table$Sigma_Shot <- round(shortlist.table$Sigma_Shot, 5)
shortlist.table$Total_Shot <- round(shortlist.table$Total_Shot,1)
shortlist.table$age <- as.numeric((shortlist.table$age))

shortlist.table %>%
        kbl() %>%
        kable_classic_2(full_width = F) %>% 
        as_image(width = 8)
```

```{r}
# Price comparison

price <- shortlist.data
price$improvement <- 0.0402886 - price$Mean_Shot

graph3 <- ggplot(price) +
        geom_point(aes(price, improvement),
                   color = "red",
                   shape = 3,
                   size = 3,
                   alpha = 0.1) +
        # geom_smooth(aes(price, improvement), 
        #             method = "lm",
        #             se = FALSE,
        #             colour = "black",
        #             alpha = 0.01) +
        stat_smooth(aes(price, improvement),
                    geom = "line",
                    alpha = 0.5,
                    se = FALSE,
                    method = "lm") +
        theme_bw() +
        xlab("Price [m]") +
        ylab("Probability Improvement over Lovren") +
        geom_text(aes(price, improvement),
                  label = price$name)

graph3
```
```{r}
graph4 <- ggplot(price) +
        geom_point(aes(price, Sigma_Shot),
                   color = "red",
                   shape = 3,
                   size = 3,
                   alpha = 0.1) +
        # geom_smooth(aes(price, improvement), 
        #             method = "lm",
        #             se = FALSE,
        #             colour = "black",
        #             alpha = 0.01) +
        stat_smooth(aes(price, Sigma_Shot),
                    geom = "line",
                    alpha = 0.5,
                    se = FALSE,
                    method = "lm") +
        theme_bw() +
        xlab("Price [m]") +
        ylab("Standard Deviation of Shot Probability per") +
        geom_text(aes(price, Sigma_Shot),
                  label = price$name)

graph4
```


```{r}
liverpool.names <- c("V. van Dijk",
                     "J. Matip",
                     "D. Lovren",
                     "N. Clyne",
                     "Alberto Moreno",
                     "A. Robertson",
                     "T. Alexander-Arnold",
                     "J. Gomez")

liverpool.table <- filter(prob.player.defenders, name %in% liverpool.names)

liverpool.table <- arrange(liverpool.table, desc(Mean_Shot))

library(kableExtra)
library(magrittr)


liverpool.table %>%
        kbl() %>%
        kable_classic_2(full_width = F) %>% 
        as_image(width = 8)
```

